FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends redsocks \
    && rm -rf /var/lib/apt/lists/*

COPY redsocks.conf /etc/redsocks.conf

ENTRYPOINT ["redsocks", "-c", "/etc/redsocks.conf"]
